apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: orderpubsub
spec:
  topic: order
  routes: 
    default: /checkout
  pubsubname: orderpubsub
# scopes:
# - orderprocessing
# - checkout